version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    reviewers:
      - "Yan-ni"
  - package-ecosystem: "npm"
    directory: "/backend"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    reviewers:
      - "Yan-ni"